name 'homebrew-extras'
maintainer 'Ryan Ovrevik'
maintainer_email 'rlo@ovrevik.com'
license 'all_rights'
description 'Installs/Configures homebrew-extras'
long_description 'Installs/Configures homebrew-extras'
version '0.1.0'
