name 'homebrew-remaining'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures homebrew-remaining'
long_description 'Installs/Configures homebrew-remaining'
version '0.1.0'
